# Generated by Django 4.2.7 on 2023-12-08 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('musician', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='musician_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_Name', models.CharField(max_length=100)),
                ('last_Name', models.CharField(max_length=50)),
                ('album_release_data', models.DateField(auto_now=True)),
                ('musician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musician.musician_model')),
            ],
        ),
    ]
