# Generated by Django 4.2.7 on 2023-12-08 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musician', '0001_initial'),
        ('album', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='musician_model',
            new_name='album_model',
        ),
    ]
