# Generated by Django 4.2.7 on 2023-12-08 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0002_rename_musician_model_album_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album_model',
            name='last_Name',
        ),
        migrations.AddField(
            model_name='album_model',
            name='Rating',
            field=models.CharField(choices=[('1', '1 Star'), ('2', '2 Stars'), ('3', '3 Stars'), ('4', '4 Stars'), ('5', '5 Stars')], default='1', max_length=1),
        ),
    ]
