# Generated by Django 4.2.7 on 2023-12-08 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0003_remove_album_model_last_name_album_model_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album_model',
            name='album_release_data',
            field=models.DateField(auto_now_add=True),
        ),
    ]
